%Name:
%Date: 23/10/2024
%Purpose: A function to calculate the moment of inertia of a tetrahedron about its centroid.

function I = tetrahedron_moment_inertia(vertices, density, center_point)

    %Calculate the centroid:
    %centroid = mean(vertices,1);

    % Unpack the vertex coordinates (each row corresponds to a vertex)
    x = vertices(:, 1)-center_point(1);
    y = vertices(:, 2)-center_point(2);
    z = vertices(:, 3)-center_point(3);
    
    % Volume of the tetrahedron (using the determinant of the Jacobian)
    J = [
        x(2) - x(1), x(3) - x(1), x(4) - x(1);
        y(2) - y(1), y(3) - y(1), y(4) - y(1);
        z(2) - z(1), z(3) - z(1), z(4) - z(1)
    ];
    DJ = abs(det(J));
    
    % Common factor in all inertia components
    factor = density * DJ / 60;
    
    % Calculate the moments of inertia
    a = factor * ...
        (y(1)^2 + y(1)*y(2) + y(2)^2 + y(1)*y(3) + y(2)*y(3) + y(3)^2 + ...
         y(1)*y(4) + y(2)*y(4) + y(3)*y(4) + y(4)^2 + ...
         z(1)^2 + z(1)*z(2) + z(2)^2 + z(1)*z(3) + z(2)*z(3) + z(3)^2 + ...
         z(1)*z(4) + z(2)*z(4) + z(3)*z(4) + z(4)^2);

    b = factor * ...
        (x(1)^2 + x(1)*x(2) + x(2)^2 + x(1)*x(3) + x(2)*x(3) + x(3)^2 + ...
         x(1)*x(4) + x(2)*x(4) + x(3)*x(4) + x(4)^2 + ...
         z(1)^2 + z(1)*z(2) + z(2)^2 + z(1)*z(3) + z(2)*z(3) + z(3)^2 + ...
         z(1)*z(4) + z(2)*z(4) + z(3)*z(4) + z(4)^2);

    c = factor * ...
        (x(1)^2 + x(1)*x(2) + x(2)^2 + x(1)*x(3) + x(2)*x(3) + x(3)^2 + ...
         x(1)*x(4) + x(2)*x(4) + x(3)*x(4) + x(4)^2 + ...
         y(1)^2 + y(1)*y(2) + y(2)^2 + y(1)*y(3) + y(2)*y(3) + y(3)^2 + ...
         y(1)*y(4) + y(2)*y(4) + y(3)*y(4) + y(4)^2);
    
    % Calculate the products of inertia
    a_prime = 0.5*factor * ...
        (2*y(1)*z(1) + y(1)*z(2) + y(1)*z(3) + y(1)*z(4) + ...
         y(2)*z(1) + 2*y(2)*z(2) + y(2)*z(3) + y(2)*z(4) + ...
         y(3)*z(1) + y(3)*z(2) + 2*y(3)*z(3) + y(3)*z(4) + ...
         y(4)*z(1) + y(4)*z(2) + y(4)*z(3) + 2*y(4)*z(4));
    b_prime = 0.5*factor * ...
        (2*x(1)*z(1) + x(1)*z(2) + x(1)*z(3) + x(1)*z(4) + ...
         x(2)*z(1) + 2*x(2)*z(2) + x(2)*z(3) + x(2)*z(4) + ...
         x(3)*z(1) + x(3)*z(2) + 2*x(3)*z(3) + x(3)*z(4) + ...
         x(4)*z(1) + x(4)*z(2) + x(4)*z(3) + 2*x(4)*z(4));
    c_prime = 0.5 * factor * ...
        (2*x(1)*y(1) + x(1)*y(2) + x(1)*y(3) + x(1)*y(4) + ...
         x(2)*y(1) + 2*x(2)*y(2) + x(2)*y(3) + x(2)*y(4) + ...
         x(3)*y(1) + x(3)*y(2) + 2*x(3)*y(3) + x(3)*y(4) + ...
         x(4)*y(1) + x(4)*y(2) + x(4)*y(3) + 2*x(4)*y(4));
    
    % Construct the inertia tensor matrix
    I = [    a,    -b_prime, -c_prime;
         -b_prime,     b,    -a_prime;
         -c_prime, -a_prime,    c     ];
end