%Name:    Isaac Nakone, Muhammad Rabay
%Date:    24/10/2024
%Purpose: This is a test script to debug the flight_section class.

clear;
clc;
close all;


aircraft_minimal = struct("payload_mass", 0.4, "structural_mass",1.0, ...
                           "motor_battery_electronics_mass", 2.0, ...
                           "lift_coefficient",2.4,"drag_coefficient", 0.1, ...
                          "reference_area",0.3721, ...
                          "motor_power_maximum", [], ...
                          "motor_efficiency", [],...
                          "battery_capacity", [], ...
                          "battery_efficiency", [],...
                          "payload_drag_coefficient", 0.01);

thrust = 300; %Newtons
initial_condition = struct("velocity_x",0,"velocity_y",0, ...
            "velocity_z", 0, "location_x",0, "location_y", 0, ...
            "location_z", 0);


take_off = flight_section(thrust, [], initial_condition, 0, aircraft_minimal,...
                true, true, false, false, false,...
               []);


initial_condition = take_off.final_condition;


climb = flight_section(20, 12, initial_condition, take_off.final_time, aircraft_minimal,...
                       true, false, true, false, false,...
                       []);